name: Test run v1

on:
  workflow_dispatch:
#  pull_request:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment v1
        run: env | grep ^GITHUB
      - name: Show ref v1
        run: echo "===============> Version from $GITHUB_REF"