# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# name: Upload Python Package

# on:
#   release:
#     types: [published]

# permissions:
#   contents: read

# jobs:
#   deploy:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.x'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         python -m pip install --upgrade twine
#         pip install build
#     - name: Build package
#       run: python -m build
#     - name: Publish package
#       uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#       with:
#         user: __token__
#         password: ${{ secrets.PYPI_TEST_API_JPMC_OSS }}
#         print_hash: true
    # - name: Publish package to test
    #   uses: alex124585
    #   with:
    #     user: __token__
    #     password:  pypi-AgENdGVzdC5weXBpLm9yZwIkMjEyMTk2NGQtZmFiOS00MzhmLThiYzUtOTI3ZGU0MWUyNmM2AAIqWzMsImU4ZjllNjUzLTA1YzItNDZjMy1iNWYwLWQ5ZTU4ZjEzMmZmMyJdAAAGIP12Klr5Tsm3E2R2jkJ6BOnGpUWXFQTOYL5AUoxV8OaD
    #     # password: ${{ secrets.PYPI_API_JPMC_OSS }}
    #     print_hash: true
    #   run: | 
    #     python -m twine upload --repository testpypi dist/*
name: Upload Python Package to PyPI

on:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.python }} - ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2022]
        python: ["cp39", "cp310", "cp311"]

    steps:
      - uses: actions/checkout@v4
      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.16.1
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:        
    name: Build Source Distribution
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz  

  upload_pypi:
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions: 
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'  
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1      
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_JPMC_OSS }}
