# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_JPMC_OSS }}
        print_hash: true
    # - name: Publish package to test
    #   uses: alex124585
    #   with:
    #     user: __token__
    #     password:  pypi-AgENdGVzdC5weXBpLm9yZwIkMjEyMTk2NGQtZmFiOS00MzhmLThiYzUtOTI3ZGU0MWUyNmM2AAIqWzMsImU4ZjllNjUzLTA1YzItNDZjMy1iNWYwLWQ5ZTU4ZjEzMmZmMyJdAAAGIP12Klr5Tsm3E2R2jkJ6BOnGpUWXFQTOYL5AUoxV8OaD
    #     # password: ${{ secrets.PYPI_API_JPMC_OSS }}
    #     print_hash: true
    #   run: | 
    #     python -m twine upload --repository testpypi dist/*

